osx_image: xcode10.2
dist: xenial
language: node_js
node_js:
  - "11"
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
script:
  - yarn dist
