language: node_js
node_js:
  - "12"
compiler: clang
matrix:
  include:
  - os: osx
    osx_image: xcode11.5
  - os: linux
    dist: bionic
  - os: windows
cache:
  yarn: true
  directories:
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn electron
  - yarn electron:build
