language: node_js
node_js:
  - "10"
compiler: clang
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
  - os: linux
    dist: xenial
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn dist
