image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.cache\electron'
  - '%USERPROFILE%\.cache\electron-builder'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 11 x64
  - choco install yarn --ignore-dependencies
  - yarn

build_script:
  - yarn dist

test: off
